In [1]:
#load dataset
import pandas as pd
df = pd.read_csv('customer_shopping.csv')

In [2]:
# Data Cleaning & Inspection
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Discount Applied        3900 non-null   object
 13  Previous Purchases      3900 non-null   int64
 14  Payment Method          3900 non-null   object
 15  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 487.6+ KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.duplicated().sum()

0

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df = pd.read_csv('customer_shopping.csv')
df.columns = df.columns.str.lower().str.replace(' ', '_') 
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [9]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [11]:
print (df.head())

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

  discount_applied  previous_purchases payment_method frequency_of_purchases
0              Yes                  14          Venmo            Fortnightly
1              Yes                   2           Cash            Fortnightly
2              Yes                  23    Credit Card                 Weekly
3              Yes                  49         PayPal                 Weekly
4              Yes                  31         PayPal               Annually

In [38]:
#create age groups
run_sql("""
    SELECT 
        CASE 
            WHEN age BETWEEN 18 AND 30 THEN 'Young Adults (18-30)'
            WHEN age BETWEEN 31 AND 45 THEN 'Adults (31-45)'
            WHEN age BETWEEN 46 AND 60 THEN 'Middle-Aged (46-60)'
            ELSE 'Seniors (61+)' 
        END AS age_group,
        COUNT(*) AS customer_count
    FROM customer_shopping
    GROUP BY age_group
    ORDER BY customer_count DESC;
""")

              age_group  customer_count
0   Middle-Aged (46-60)            1135
1        Adults (31-45)            1093
2  Young Adults (18-30)             949
3         Seniors (61+)             723

In [13]:
df[['age', 'age_group']].head(10)

   age             age_group
0   55   Middle-Aged (46-60)
1   19  Young Adults (18-30)
2   50   Middle-Aged (46-60)
3   21  Young Adults (18-30)
4   45        Adults (31-45)
5   46   Middle-Aged (46-60)
6   63         Seniors (61+)
7   27  Young Adults (18-30)
8   26  Young Adults (18-30)
9   57   Middle-Aged (46-60)

In [14]:
# create column purchase_frequency_days
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Annually': 365
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [16]:
df[['discount_applied']].head(10)

  discount_applied
0              Yes
1              Yes
2              Yes
3              Yes
4              Yes
5              Yes
6              Yes
7              Yes
8              Yes
9              Yes

In [17]:
df.to_csv('cleaned_customer_shopping.csv', index=False)
print("File saved successfully!")

File saved successfully!

In [18]:
import sqlite3

In [19]:
conn = sqlite3.connect('retail_shop.db')

In [20]:
df.to_sql('customer_shopping', conn, if_exists='replace', index=False)

3900

In [21]:
conn.close()

In [22]:
import pandas as pd
import sqlite3
import pandas as pd
import sqlite3

def run_sql(query_string):
    """Automatically connects to the database, runs the SQL query, and returns a DataFrame."""
    conn = sqlite3.connect('retail_shop.db')
    result_df = pd.read_sql(query_string, conn)
    conn.close()
    return result_df

In [23]:
##what is the total revenue generated by male versus female customers 
run_sql("""
    SELECT gender, SUM(purchase_amount) AS revenue
    FROM customer_shopping
    GROUP BY gender;
""")

   gender  revenue
0  Female    75191
1    Male   157890

In [24]:
##which are top 5 products with the highest review rating
run_sql("""
    SELECT item_purchased, category, ROUND(AVG(review_rating), 2) AS avg_rating
    FROM customer_shopping
    GROUP BY item_purchased, category
    ORDER BY avg_rating DESC
    LIMIT 5;
""")

  item_purchased     category  avg_rating
0         Gloves  Accessories        3.86
1        Sandals     Footwear        3.84
2          Boots     Footwear        3.81
3            Hat  Accessories        3.81
4        Handbag  Accessories        3.78

In [25]:
##compare the average purchase amount between standard and express shipping
run_sql("PRAGMA table_info(customer_shopping);")

    cid                     name     type  notnull dflt_value  pk
0     0              customer_id  INTEGER        0       None   0
1     1                      age  INTEGER        0       None   0
2     2                   gender     TEXT        0       None   0
3     3           item_purchased     TEXT        0       None   0
4     4                 category     TEXT        0       None   0
5     5          purchase_amount  INTEGER        0       None   0
6     6                 location     TEXT        0       None   0
7     7                     size     TEXT        0       None   0
8     8                    color     TEXT        0       None   0
9     9                   season     TEXT        0       None   0
10   10            review_rating     REAL        0       None   0
11   11      subscription_status     TEXT        0       None   0
12   12         discount_applied     TEXT        0       None   0
13   13       previous_purchases  INTEGER        0       None   0
14   14           payment_method     TEXT        0       None   0
15   15   frequency_of_purchases     TEXT        0       None   0
16   16                age_group     TEXT        0       None   0
17   17  purchase_frequency_days  INTEGER        0       None   0

In [26]:
run_sql("""
    SELECT payment_method, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount, COUNT(*) AS total_transactions
    FROM customer_shopping
    GROUP BY payment_method
    ORDER BY avg_purchase_amount DESC;
""")

  payment_method  avg_purchase_amount  total_transactions
0     Debit Card                60.92                 636
1    Credit Card                60.07                 671
2  Bank Transfer                59.71                 612
3           Cash                59.70                 670
4         PayPal                59.25                 677
5          Venmo                58.95                 634

In [27]:
##do subscribed customers spend more? compare average spend and total revenue between subscriber and non subscriber
run_sql("""
    SELECT subscription_status, 
           ROUND(AVG(purchase_amount), 2) AS avg_spend, 
           SUM(purchase_amount) AS total_revenue,
           COUNT(*) AS total_transactions
    FROM customer_shopping
    GROUP BY subscription_status;
""")

  subscription_status  avg_spend  total_revenue  total_transactions
0                  No      59.87         170436                2847
1                 Yes      59.49          62645                1053

In [28]:
##which five product have the highest percentage of purchases with discount applied
run_sql("""
    SELECT item_purchased, 
           COUNT(*) AS total_purchases,
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
           ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_percentage
    FROM customer_shopping
    GROUP BY item_purchased
    ORDER BY discount_percentage DESC
    LIMIT 5;
""")

  item_purchased  total_purchases  discounted_purchases  discount_percentage
0            Hat              154                    77                50.00
1       Sneakers              145                    72                49.66
2           Coat              161                    79                49.07
3        Sweater              164                    79                48.17
4          Pants              171                    81                47.37

In [29]:
##segment customers in to new returnning and loyal based on their total number of pervious purchases, and show the count of each segment
run_sql("""
    SELECT 
        CASE 
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment,
        COUNT(*) AS customer_count
    FROM customer_shopping
    GROUP BY customer_segment
    ORDER BY customer_count DESC;
""")

  customer_segment  customer_count
0            Loyal            3476
1        Returning             424

In [30]:
##what are top 3 most purchased product within category
run_sql("""
    WITH ranked_products AS (
        SELECT category, 
               item_purchased, 
               COUNT(*) AS total_purchased,
               ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as rank_num
        FROM customer_shopping
        GROUP BY category, item_purchased
    )
    SELECT category, item_purchased, total_purchased
    FROM ranked_products
    WHERE rank_num <= 3;
""")

       category item_purchased  total_purchased
0   Accessories        Jewelry              171
1   Accessories     Sunglasses              161
2   Accessories           Belt              161
3      Clothing          Pants              171
4      Clothing         Blouse              171
5      Clothing          Shirt              169
6      Footwear        Sandals              160
7      Footwear          Shoes              150
8      Footwear       Sneakers              145
9     Outerwear         Jacket              163
10    Outerwear           Coat              161

In [31]:
##Are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe
import pandas as pd
import sqlite3

def run_sql(query_string):
    """Automatically connects to the database, runs the SQL query, and returns a DataFrame."""
    conn = sqlite3.connect('retail_shop.db')
    result_df = pd.read_sql(query_string, conn)
    conn.close()
    return result_df

In [33]:
run_sql("""
    SELECT payment_method, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount, COUNT(*) AS total_transactions
    FROM customer_shopping
    GROUP BY payment_method
    ORDER BY avg_purchase_amount DESC;
""")

  payment_method  avg_purchase_amount  total_transactions
0     Debit Card                60.92                 636
1    Credit Card                60.07                 671
2  Bank Transfer                59.71                 612
3           Cash                59.70                 670
4         PayPal                59.25                 677
5          Venmo                58.95                 634

In [34]:
## customers who used discounts and spent above the average
run_sql("""
    SELECT 
        subscription_status, 
        COUNT(*) as total_transactions,
        ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
    FROM customer_shopping 
    WHERE discount_applied = 'Yes' 
      AND purchase_amount > (
          SELECT AVG(purchase_amount) 
          FROM customer_shopping
      )
    GROUP BY subscription_status;
""")

  subscription_status  total_transactions  avg_purchase_amount
0                  No                 310                79.72
1                 Yes                 529                79.83

In [35]:
##which five product have the highest percentage of purchases with discount applied
run_sql("""
    SELECT item_purchased, 
           COUNT(*) AS total_purchases,
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
           ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_percentage
    FROM customer_shopping
    GROUP BY item_purchased
    ORDER BY discount_percentage DESC
    LIMIT 5;
""")

  item_purchased  total_purchases  discounted_purchases  discount_percentage
0            Hat              154                    77                50.00
1       Sneakers              145                    72                49.66
2           Coat              161                    79                49.07
3        Sweater              164                    79                48.17
4          Pants              171                    81                47.37

In [2]:
import pandas as pd
import sqlite3

def run_sql(query_string):
    """Automatically connects to the database, runs the SQL query, and returns a DataFrame."""
    conn = sqlite3.connect('retail_shop.db')
    result_df = pd.read_sql(query_string, conn)
    conn.close()
    return result_df

In [3]:
## what is the revenue contribution of each age group

run_sql("""    
    SELECT 
        CASE 
            WHEN age BETWEEN 18 AND 29 THEN '18-29 (Young Adult)'
            WHEN age BETWEEN 30 AND 44 THEN '30-44 (Adult)'
            WHEN age BETWEEN 45 AND 59 THEN '45-59 (Middle-Aged)'
            ELSE '60+ (Senior)'
        END AS age_group,
        SUM(purchase_amount) AS total_revenue,
        ROUND(100.0 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer_shopping), 2) AS revenue_percentage
    FROM customer_shopping
    GROUP BY age_group
    ORDER BY total_revenue DESC;
""")

             age_group  total_revenue  revenue_percentage
0  45-59 (Middle-Aged)          67711               29.05
1  45-59 (Middle-Aged)          64927               27.86
2  18-29 (Young Adult)          57279               24.57
3         60+ (Senior)          43164               18.52

In [4]:
# Export customer_shopping table to a CSV file
df = run_sql("SELECT * FROM customer_shopping;")
df.to_csv("customer_shopping_data.csv", index=False)
print("Data exported successfully!")

Data exported successfully!